// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    user_id,
    event_type,
    ip_address,
    details
) VALUES (
    $1, $2, $3, $4
) RETURNING id, created_at
`

type CreateAuditEventParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	EventType string      `json:"event_type"`
	IpAddress pgtype.Text `json:"ip_address"`
	Details   []byte      `json:"details"`
}

type CreateAuditEventRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (CreateAuditEventRow, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.UserID,
		arg.EventType,
		arg.IpAddress,
		arg.Details,
	)
	var i CreateAuditEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
