// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batches.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO transaction_import_batches (
    user_id, source_filename
) VALUES (
    $1, $2
) RETURNING id, user_id, source_filename, created_at
`

type CreateImportBatchParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	SourceFilename pgtype.Text `json:"source_filename"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (TransactionImportBatch, error) {
	row := q.db.QueryRow(ctx, createImportBatch, arg.UserID, arg.SourceFilename)
	var i TransactionImportBatch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceFilename,
		&i.CreatedAt,
	)
	return i, err
}
