// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hmrc.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHMRCConnection = `-- name: DeleteHMRCConnection :exec
DELETE FROM hmrc_connections
WHERE user_id = $1
`

func (q *Queries) DeleteHMRCConnection(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHMRCConnection, userID)
	return err
}

const getHMRCConnectionByUserID = `-- name: GetHMRCConnectionByUserID :one
SELECT id, user_id, mtd_id, access_token, refresh_token, token_expiry, created_at, updated_at FROM hmrc_connections
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetHMRCConnectionByUserID(ctx context.Context, userID pgtype.UUID) (HmrcConnection, error) {
	row := q.db.QueryRow(ctx, getHMRCConnectionByUserID, userID)
	var i HmrcConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MtdID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertHMRCConnection = `-- name: UpsertHMRCConnection :one
INSERT INTO hmrc_connections (user_id, mtd_id, access_token, refresh_token, token_expiry, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (user_id) DO UPDATE
SET mtd_id = EXCLUDED.mtd_id,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    token_expiry = EXCLUDED.token_expiry,
    updated_at = NOW()
RETURNING id, user_id, mtd_id, token_expiry
`

type UpsertHMRCConnectionParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	MtdID        string             `json:"mtd_id"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `json:"token_expiry"`
}

type UpsertHMRCConnectionRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	MtdID       string             `json:"mtd_id"`
	TokenExpiry pgtype.Timestamptz `json:"token_expiry"`
}

func (q *Queries) UpsertHMRCConnection(ctx context.Context, arg UpsertHMRCConnectionParams) (UpsertHMRCConnectionRow, error) {
	row := q.db.QueryRow(ctx, upsertHMRCConnection,
		arg.UserID,
		arg.MtdID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	var i UpsertHMRCConnectionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MtdID,
		&i.TokenExpiry,
	)
	return i, err
}
