// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	EventType string             `json:"event_type"`
	Details   []byte             `json:"details"`
	IpAddress pgtype.Text        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MappingProfile struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	Fingerprint  string             `json:"fingerprint"`
	MappingRules []byte             `json:"mapping_rules"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OauthToken struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expiry       pgtype.Timestamptz `json:"expiry"`
	Scope        string             `json:"scope"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Receipt struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	CorrelationID    string             `json:"correlation_id"`
	ReceiptTimestamp pgtype.Timestamptz `json:"receipt_timestamp"`
	SubmissionType   string             `json:"submission_type"`
	PeriodKey        string             `json:"period_key"`
	PayloadHash      string             `json:"payload_hash"`
	TotalsJson       []byte             `json:"totals_json"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	Token  string             `json:"token"`
	Expiry pgtype.Timestamptz `json:"expiry"`
	Data   []byte             `json:"data"`
}

type Transaction struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ImportBatchID pgtype.UUID        `json:"import_batch_id"`
	BankDate      pgtype.Date        `json:"bank_date"`
	Description   string             `json:"description"`
	Amount        pgtype.Numeric     `json:"amount"`
	Status        string             `json:"status"`
	Stream        pgtype.Text        `json:"stream"`
	Category      pgtype.Text        `json:"category"`
	SourceRowHash pgtype.Text        `json:"source_row_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type TransactionImportBatch struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	SourceFilename pgtype.Text        `json:"source_filename"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Waitlist struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
