// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, user_id, provider, access_token, refresh_token, expiry, scope, created_at, updated_at FROM oauth_tokens
WHERE user_id = $1 AND provider = $2
LIMIT 1
`

type GetOAuthTokenParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthToken, arg.UserID, arg.Provider)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expiry,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthToken = `-- name: UpsertOAuthToken :one
INSERT INTO oauth_tokens (
    user_id, provider, access_token, refresh_token, expiry, scope, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
ON CONFLICT (id) DO UPDATE -- Note: You might need a unique constraint on (user_id, provider) for this to work perfectly, or just use ID.
SET access_token = $3, refresh_token = $4, expiry = $5, updated_at = NOW()
RETURNING id, user_id, provider, access_token, refresh_token, expiry, scope, created_at, updated_at
`

type UpsertOAuthTokenParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	AccessToken  string             `json:"access_token"`
	RefreshToken string             `json:"refresh_token"`
	Expiry       pgtype.Timestamptz `json:"expiry"`
	Scope        string             `json:"scope"`
}

// Saves or updates the token. If user already has one, we overwrite it.
// actually, standard practice is usually finding by user_id. Let's stick to simple Insert/Update for now.
func (q *Queries) UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, upsertOAuthToken,
		arg.UserID,
		arg.Provider,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Expiry,
		arg.Scope,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Expiry,
		&i.Scope,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
