// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (TransactionImportBatch, error)
	CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteSession(ctx context.Context, token string) error
	// The Purge. Runs after submission.
	DeleteTransactionsForPeriod(ctx context.Context, arg DeleteTransactionsForPeriodParams) error
	// UPDATED: Now counts Trade and Property separately
	GetDashboardStats(ctx context.Context, userID pgtype.UUID) (GetDashboardStatsRow, error)
	GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error)
	GetSession(ctx context.Context, token string) (Session, error)
	// Fetches business data for a SPECIFIC stream (Trade OR Property)
	GetSubmissionData(ctx context.Context, arg GetSubmissionDataParams) ([]GetSubmissionDataRow, error)
	// Used for the "Swiping" UI. Returns a page of items.
	GetUnprocessedTransactions(ctx context.Context, arg GetUnprocessedTransactionsParams) ([]Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListReceipts(ctx context.Context, userID pgtype.UUID) ([]Receipt, error)
	// The "Swipe Left" action. No stream/category needed.
	MarkTransactionPersonal(ctx context.Context, arg MarkTransactionPersonalParams) (Transaction, error)
	// The core "Swipe Right" action.
	UpdateTransactionCategory(ctx context.Context, arg UpdateTransactionCategoryParams) (Transaction, error)
	// Saves or updates the token. If user already has one, we overwrite it.
	// actually, standard practice is usually finding by user_id. Let's stick to simple Insert/Update for now.
	UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error)
}

var _ Querier = (*Queries)(nil)
