// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (
    user_id, correlation_id, receipt_timestamp, submission_type, period_key, payload_hash, totals_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, correlation_id, receipt_timestamp, submission_type, period_key, payload_hash, totals_json, created_at
`

type CreateReceiptParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	CorrelationID    string             `json:"correlation_id"`
	ReceiptTimestamp pgtype.Timestamptz `json:"receipt_timestamp"`
	SubmissionType   string             `json:"submission_type"`
	PeriodKey        string             `json:"period_key"`
	PayloadHash      string             `json:"payload_hash"`
	TotalsJson       []byte             `json:"totals_json"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, createReceipt,
		arg.UserID,
		arg.CorrelationID,
		arg.ReceiptTimestamp,
		arg.SubmissionType,
		arg.PeriodKey,
		arg.PayloadHash,
		arg.TotalsJson,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CorrelationID,
		&i.ReceiptTimestamp,
		&i.SubmissionType,
		&i.PeriodKey,
		&i.PayloadHash,
		&i.TotalsJson,
		&i.CreatedAt,
	)
	return i, err
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, user_id, correlation_id, receipt_timestamp, submission_type, period_key, payload_hash, totals_json, created_at FROM receipts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReceipts(ctx context.Context, userID pgtype.UUID) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, listReceipts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CorrelationID,
			&i.ReceiptTimestamp,
			&i.SubmissionType,
			&i.PeriodKey,
			&i.PayloadHash,
			&i.TotalsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
