// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, import_batch_id, bank_date, description, amount, source_row_hash
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, import_batch_id, bank_date, description, amount, status, stream, category, source_row_hash, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID        pgtype.UUID    `json:"user_id"`
	ImportBatchID pgtype.UUID    `json:"import_batch_id"`
	BankDate      pgtype.Date    `json:"bank_date"`
	Description   string         `json:"description"`
	Amount        pgtype.Numeric `json:"amount"`
	SourceRowHash pgtype.Text    `json:"source_row_hash"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.ImportBatchID,
		arg.BankDate,
		arg.Description,
		arg.Amount,
		arg.SourceRowHash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImportBatchID,
		&i.BankDate,
		&i.Description,
		&i.Amount,
		&i.Status,
		&i.Stream,
		&i.Category,
		&i.SourceRowHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransactionsForPeriod = `-- name: DeleteTransactionsForPeriod :exec
DELETE FROM transactions
WHERE user_id = $1
  AND status = 'business'
  AND stream = $2
  AND bank_date >= $3::date
  AND bank_date <= $4::date
`

type DeleteTransactionsForPeriodParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Stream    pgtype.Text `json:"stream"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// The Purge. Runs after submission.
func (q *Queries) DeleteTransactionsForPeriod(ctx context.Context, arg DeleteTransactionsForPeriodParams) error {
	_, err := q.db.Exec(ctx, deleteTransactionsForPeriod,
		arg.UserID,
		arg.Stream,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'unprocessed') as unprocessed_count,
    COUNT(*) FILTER (WHERE status = 'business' AND stream = 'TRADE') as trade_count,
    COUNT(*) FILTER (WHERE status = 'business' AND stream = 'PROPERTY') as property_count
FROM transactions
WHERE user_id = $1
`

type GetDashboardStatsRow struct {
	UnprocessedCount int64 `json:"unprocessed_count"`
	TradeCount       int64 `json:"trade_count"`
	PropertyCount    int64 `json:"property_count"`
}

// UPDATED: Now counts Trade and Property separately
func (q *Queries) GetDashboardStats(ctx context.Context, userID pgtype.UUID) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats, userID)
	var i GetDashboardStatsRow
	err := row.Scan(&i.UnprocessedCount, &i.TradeCount, &i.PropertyCount)
	return i, err
}

const getSubmissionData = `-- name: GetSubmissionData :many
SELECT category, SUM(amount) as total_amount
FROM transactions
WHERE user_id = $1
  AND status = 'business'
  AND stream = $2 -- Passed in as 'TRADE' or 'PROPERTY'
  AND bank_date >= $3::date
  AND bank_date <= $4::date
GROUP BY category
`

type GetSubmissionDataParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Stream    pgtype.Text `json:"stream"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetSubmissionDataRow struct {
	Category    pgtype.Text `json:"category"`
	TotalAmount int64       `json:"total_amount"`
}

// Fetches business data for a SPECIFIC stream (Trade OR Property)
func (q *Queries) GetSubmissionData(ctx context.Context, arg GetSubmissionDataParams) ([]GetSubmissionDataRow, error) {
	rows, err := q.db.Query(ctx, getSubmissionData,
		arg.UserID,
		arg.Stream,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubmissionDataRow
	for rows.Next() {
		var i GetSubmissionDataRow
		if err := rows.Scan(&i.Category, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnprocessedTransactions = `-- name: GetUnprocessedTransactions :many
SELECT id, user_id, import_batch_id, bank_date, description, amount, status, stream, category, source_row_hash, created_at, updated_at FROM transactions
WHERE user_id = $1
  AND status = 'unprocessed'
ORDER BY bank_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type GetUnprocessedTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Used for the "Swiping" UI. Returns a page of items.
func (q *Queries) GetUnprocessedTransactions(ctx context.Context, arg GetUnprocessedTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUnprocessedTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ImportBatchID,
			&i.BankDate,
			&i.Description,
			&i.Amount,
			&i.Status,
			&i.Stream,
			&i.Category,
			&i.SourceRowHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionPersonal = `-- name: MarkTransactionPersonal :one
UPDATE transactions
SET status = 'personal',
    stream = NULL,
    category = NULL,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, import_batch_id, bank_date, description, amount, status, stream, category, source_row_hash, created_at, updated_at
`

type MarkTransactionPersonalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// The "Swipe Left" action. No stream/category needed.
func (q *Queries) MarkTransactionPersonal(ctx context.Context, arg MarkTransactionPersonalParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionPersonal, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImportBatchID,
		&i.BankDate,
		&i.Description,
		&i.Amount,
		&i.Status,
		&i.Stream,
		&i.Category,
		&i.SourceRowHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionCategory = `-- name: UpdateTransactionCategory :one
UPDATE transactions
SET status = $2,
    stream = $3,
    category = $4,
    updated_at = NOW()
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, import_batch_id, bank_date, description, amount, status, stream, category, source_row_hash, created_at, updated_at
`

type UpdateTransactionCategoryParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
	Stream   pgtype.Text `json:"stream"`
	Category pgtype.Text `json:"category"`
	UserID   pgtype.UUID `json:"user_id"`
}

// The core "Swipe Right" action.
func (q *Queries) UpdateTransactionCategory(ctx context.Context, arg UpdateTransactionCategoryParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionCategory,
		arg.ID,
		arg.Status,
		arg.Stream,
		arg.Category,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ImportBatchID,
		&i.BankDate,
		&i.Description,
		&i.Amount,
		&i.Status,
		&i.Stream,
		&i.Category,
		&i.SourceRowHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
