// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waitlist.sql

package database

import (
	"context"
)

const checkWaitlistEmail = `-- name: CheckWaitlistEmail :one
SELECT EXISTS(SELECT 1 FROM waitlist WHERE email = $1)
`

func (q *Queries) CheckWaitlistEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkWaitlistEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createWaitlistEntry = `-- name: CreateWaitlistEntry :one
INSERT INTO waitlist (
    email
) VALUES (
    $1
) RETURNING id, email, created_at
`

func (q *Queries) CreateWaitlistEntry(ctx context.Context, email string) (Waitlist, error) {
	row := q.db.QueryRow(ctx, createWaitlistEntry, email)
	var i Waitlist
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}
