repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.7.2
    hooks:
      - id: golangci-lint
        args: ["--timeout=5m", "./cmd/...", "./internal/..."]

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
      - id: go-fmt

  - repo: local
    hooks:
      - id: go-vet-all
        name: go-vet
        entry: go vet ./...
        language: system
        pass_filenames: false
        files: \.go$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
