version: '3.8'

secrets:
  db_password:
    file: ./secrets/db_password.txt

services:
  postgres:
    container_name: dividr-postgres
    image: postgres:17
    environment:
      POSTGRES_USER: dividr
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: dividr
    secrets:
      - db_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  dividr:
    container_name: dividr
    image: dividr:latest
      #image: ghcr.io/rhysmcneill/dividr:0.3.0
    environment:
      APP_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: dividr
      DB_NAME: dividr
    secrets:
      - db_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  db_data:
