// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package legal

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Privacy() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p class=\"lead\">At Dividr, we take your privacy seriously. This policy explains how we handle your data, specifically regarding the HMRC Making Tax Digital (MTD) submission process.</p><h3>1. Data Collection</h3><p>We collect your email address for account management and waitlist notification purposes. When you upload a spreadsheet for processing, that file is transmitted securely to our servers.</p><h3>2. Data Retention (The \"Zero Retention\" Policy)</h3><p>We adhere to a strict zero-retention policy for financial data:</p><ul><li><strong>Spreadsheets:</strong> Uploaded files are held in memory only for the duration of the parsing and submission process.</li><li><strong>Submission Data:</strong> Once HMRC confirms receipt, we delete the transaction data from our servers within 24 hours.</li><li><strong>Logs:</strong> We retain only the submission receipt ID and timestamp for audit purposes.</li></ul><h3>3. Third Parties</h3><p>We do not sell your data. We share data only with:</p><ul><li><strong>HMRC:</strong> To fulfill the MTD submission request you initiated.</li><li><strong>Infrastructure Providers:</strong> Our servers are hosted on AWS (London Region).</li></ul><h3>4. Contact Us</h3><p>If you have questions about this policy, please contact support@dividr.app.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Privacy Policy", "January 12, 2026").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
