// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package legal

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Security() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p class=\"lead text-xl text-zinc-300\">Security is our primary feature. Because we handle financial data, we design our systems to hold as little sensitive information as possible (\"Data Minimization\").</p><h3>1. Infrastructure & Encryption</h3><p>Our infrastructure is hosted on AWS (London Region) to ensure UK data sovereignty compliance.</p><ul><li><strong>In Transit:</strong> All data is encrypted via TLS 1.3 during transmission.</li><li><strong>At Rest:</strong> OAuth tokens and user metadata are encrypted using AES-256 before being stored in our database.</li></ul><h3>2. Minimal Retention Architecture</h3><p>Unlike traditional accounting software, we do not want to be the \"source of truth\" for your financial history.</p><ul><li>Files you upload are processed in memory and immediately discarded.</li><li>Parsed transaction rows are stored in a temporary \"staging\" table.</li><li><strong>The Purge:</strong> Upon successful submission to HMRC (or after 24 hours of inactivity), raw transaction data is permanently deleted from our servers.</li></ul><h3>3. Incident Support</h3><p>Because we delete your raw data, we cannot \"look up\" your past transactions to debug issues.</p><p>If you need support regarding a submission, you must provide the <strong>Receipt ID</strong> or <strong>Correlation ID</strong> provided at the time of submission. This allows us to trace the audit logs without accessing your financial contents.</p><h3>4. Vulnerability Reporting</h3><p>If you discover a security vulnerability, please report it to security@dividr.app. We appreciate your help in keeping the platform safe.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Security", "January 12, 2026").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
