// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package legal

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Terms() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p class=\"lead text-xl text-zinc-300\">By using Dividr (\"The Service\"), you agree to the following terms. Please read them carefully, particularly the sections regarding our \"Beta\" status and limitations of liability.</p><h3>1. Beta Status</h3><p>Dividr is currently in a <strong>Public Beta</strong> phase. This means:</p><ul><li>The Service may experience occasional downtime or errors.</li><li>Features may change, break, or disappear without notice.</li><li>We do not guarantee that the Service is suitable for mission-critical accounting tasks at this stage.</li></ul><h3>2. Not Financial or Tax Advice</h3><p>Dividr is a technical bridge for data submission. <strong>We are not accountants or tax advisors.</strong></p><ul><li>We do not verify the accuracy of the numbers in your spreadsheet.</li><li>We do not advise on which expenses are allowable.</li><li>It is your sole responsibility to ensure your tax return is accurate before submission to HMRC.</li></ul><h3>3. Limitation of Liability</h3><p>To the maximum extent permitted by law, Dividr excludes all liability for any indirect or consequential loss (including loss of data, profit, or business opportunities) arising from your use of the Service.</p><p>Our total liability to you for any direct losses arising from the use of the Service shall be limited to the amount of subscription fees paid by you in the 12 months preceding the event.</p><h3>4. Account Termination</h3><p>We reserve the right to suspend or terminate accounts that abuse the API, attempt to bypass security controls, or use the Service for illegal purposes.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Terms of Service", "January 12, 2026").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
